CREATE TABLE "countries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "code" varchar(10) UNIQUE,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "brands" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "country_id" int NOT NULL,
  "description" text,
  "website_url" varchar(255),
  "is_cruelty_free" boolean DEFAULT false,
  "is_vegan" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "product_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "parent_category_id" int,
  "description" text
);

CREATE TABLE "age_groups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "min_age" int,
  "max_age" int,
  "description" text
);

CREATE TABLE "genders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "budget_ranges" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "min_price" decimal(10,2) NOT NULL,
  "max_price" decimal(10,2),
  "currency" varchar(10) DEFAULT 'INR',
  "description" text
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brand_id" int NOT NULL,
  "category_id" int NOT NULL,
  "name" varchar(200) NOT NULL,
  "slug" varchar(200) UNIQUE NOT NULL,
  "description" text,
  "is_active" boolean DEFAULT true,
  "launch_date" date,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "product_variants" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "variant_name" varchar(150),
  "sku" varchar(100) UNIQUE,
  "price" decimal(10,2),
  "currency" varchar(10) DEFAULT 'INR',
  "size_ml" decimal(10,2),
  "size_g" decimal(10,2),
  "stock_status" varchar(50),
  "is_default" boolean DEFAULT false
);

CREATE TABLE "attribute_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "data_type" varchar(30) NOT NULL,
  "unit" varchar(30),
  "category_id" int
);

CREATE TABLE "product_attribute_values" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "variant_id" int,
  "attribute_type_id" int NOT NULL,
  "value_text" varchar(255),
  "value_number" decimal(10,2),
  "value_boolean" boolean,
  "value_enum" varchar(100),
  "unit" varchar(30)
);

CREATE TABLE "ingredients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE NOT NULL,
  "ingredient_group" varchar(100),
  "description" text,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "product_ingredients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "ingredient_id" int NOT NULL,
  "percentage" decimal(5,2),
  "is_highlighted" boolean DEFAULT false,
  "function" varchar(100)
);

CREATE TABLE "concerns" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "product_concerns" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "concern_id" int NOT NULL
);

CREATE TABLE "product_age_groups" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "age_group_id" int NOT NULL
);

CREATE TABLE "product_genders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "gender_id" int NOT NULL
);

CREATE TABLE "product_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "variant_id" int,
  "image_url" varchar(500) NOT NULL,
  "image_type" varchar(50),
  "sort_order" int DEFAULT 0
);

CREATE TABLE "purchase_sources" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "variant_id" int,
  "retailer_name" varchar(150),
  "retailer_url" varchar(500) NOT NULL,
  "affiliate_flag" boolean DEFAULT false,
  "country_id" int
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150),
  "email" varchar(255) UNIQUE,
  "password_hash" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "skin_profiles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "age_group_id" int,
  "gender_id" int,
  "skin_type" varchar(50),
  "country_preference" varchar(50),
  "budget_range_id" int,
  "routine_type" varchar(30),
  "routine_complexity" varchar(30),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "skin_profile_concerns" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "skin_profile_id" int NOT NULL,
  "concern_id" int NOT NULL
);

CREATE TABLE "routine_recommendations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "product_id" int NOT NULL,
  "routine_type" varchar(30),
  "match_score" decimal(5,2),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "saved_routines" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "routine_name" varchar(150),
  "routine_type" varchar(30),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "saved_routine_products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "saved_routine_id" int NOT NULL,
  "product_id" int NOT NULL,
  "routine_step" varchar(100),
  "sort_order" int DEFAULT 0
);

ALTER TABLE "brands" ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_categories" ADD FOREIGN KEY ("parent_category_id") REFERENCES "product_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("brand_id") REFERENCES "brands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "product_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_variants" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attribute_types" ADD FOREIGN KEY ("category_id") REFERENCES "product_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_attribute_values" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_attribute_values" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_attribute_values" ADD FOREIGN KEY ("attribute_type_id") REFERENCES "attribute_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_ingredients" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_ingredients" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_concerns" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_concerns" ADD FOREIGN KEY ("concern_id") REFERENCES "concerns" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_age_groups" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_age_groups" ADD FOREIGN KEY ("age_group_id") REFERENCES "age_groups" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_genders" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_genders" ADD FOREIGN KEY ("gender_id") REFERENCES "genders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_images" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_sources" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_sources" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_sources" ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skin_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skin_profiles" ADD FOREIGN KEY ("age_group_id") REFERENCES "age_groups" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skin_profiles" ADD FOREIGN KEY ("gender_id") REFERENCES "genders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skin_profiles" ADD FOREIGN KEY ("budget_range_id") REFERENCES "budget_ranges" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skin_profile_concerns" ADD FOREIGN KEY ("skin_profile_id") REFERENCES "skin_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "skin_profile_concerns" ADD FOREIGN KEY ("concern_id") REFERENCES "concerns" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "routine_recommendations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "routine_recommendations" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saved_routines" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saved_routine_products" ADD FOREIGN KEY ("saved_routine_id") REFERENCES "saved_routines" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saved_routine_products" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;
